const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const VALIDATION_ERROR = 401;
const INTERDICTION_ERROR = 403;
const ALREADY_EXIST_ERROR = 409;
module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  VALIDATION_ERROR,
  INTERDICTION_ERROR,
  ALREADY_EXIST_ERROR,
};
